name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#refs/heads/}"
          VERSION="${VERSION#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/readability-proxy:${{ env.VERSION }} \
            -t ghcr.io/${{ github.repository }}/readability-proxy:latest \
            .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/readability-proxy:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}/readability-proxy:latest